#!/bin/zsh
BRANCH=$(git branch --show-current)
URL=$(git remote -v |
head -n 1 |
awk -F "@" '{print $2}' |
awk -F " " '{print $1}' |
sed 's/:/\//g' |
sed 's/.git//g' |
awk '{print "http://"$1"/compare/"}' )
PR_URL=$URL$BRANCH"?expand=1"
open $PR_URL
